### ISSUE TITLE
Ulimit.soft must be an integer Failed to execute script docker-compose

### ISSUE THREAD

**Issue by Cuica20** [jhipster/jhipster-console#59]
CMD> docker-compose up -d
Starting javiercuicapuza_jhipster-logstash_1
Starting javiercuicapuza_jhipster-console_1
Starting javiercuicapuza_jhipster-alerter_1

ERROR: for jhipster-elasticsearch  Ulimit.soft must be an integer
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 64, in main
  File "compose\cli\main.py", line 116, in perform_command
  File "compose\cli\main.py", line 876, in up
  File "compose\project.py", line 416, in up
  File "compose\parallel.py", line 66, in parallel_execute
ValueError: Ulimit.soft must be an integer
Failed to execute script docker-compose

**Comment by PierreBesson** [comment]
This should not happen on the newest release
